## Short Data

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sovai as sov
sov.token_auth(token="your_token_here")

### Short Interest & Overshorted

In [3]:
df_short = sov.data("short/over_shorted", tickers=["AAPL", "MSFT"])

/short/over_shorted
Requesting URL: https://data.sov.ai/short/over_shorted with params: {'tickers': 'AAPL,MSFT', 'parquet': 'True'}
Response Status: 200
Response Content-Type: application/json
tickers is: ['AAPL', 'MSFT']
{'tickers': 'AAPL,MSFT', 'parquet': 'True'}
tickers is: ['AAPL', 'MSFT']
It reached the DF
It passed the DF

**All Data:** This is a very large file (2 mins wait)

In [4]:
df_short_all = sov.data("short/over_shorted")

/short/over_shorted
Requesting URL: https://data.sov.ai/short/over_shorted with params: {'parquet': 'True'}
Response Status: 200
Response Content-Type: application/json
tickers is None
{'parquet': 'True'}
tickers is:
All ticker Initialized
https://s3.wasabisys.com/sovai-short/processed/over_shorted_frame.parquet?AWSAccessKeyId=KI07G4DK9XP5EC0NH1VU&Signature=mwS4nufJaTB8ynZY4Z81GItDztY%3D&Expires=1718873645  (download link)

In [5]:
df_short_all

                   over_shorted  over_shorted_chg  short_interest  \
ticker date
A      1999-12-31        -0.178             0.000      886789.000
       2000-01-07        -0.208            -0.031      886789.000
       2000-01-14        -0.192             0.017      886789.000
       2000-01-21        -0.201            -0.010      886789.000
       2000-01-28        -0.191             0.010      886789.000
...                         ...               ...             ...
ZZ     2013-02-15         0.456             0.102    18287136.000
       2013-02-22         0.395            -0.060    18287136.000
       2013-03-01         0.391            -0.005    18287136.000
       2013-03-08         0.329            -0.062    18570636.000
       2013-03-15         0.384             0.055    19504380.000

                   number_of_shares  short_percentage  short_prediction  \
ticker date
A      1999-12-31     444999360.000             0.332             0.510
       2000-01-07     445000000.000             0.332             0.540
       2000-01-14     445000000.000             0.332             0.523
       2000-01-21     445000736.000             0.332             0.534
       2000-01-28     451999712.000             0.331             0.522
...                             ...               ...               ...
ZZ     2013-02-15     100958904.000             0.887             0.431
       2013-02-22     100963304.000             0.887             0.491
       2013-03-01     100958904.000             0.888             0.497
       2013-03-08     100954544.000             0.888             0.559
       2013-03-15     100958904.000             0.890             0.506

                   days_to_cover  market_cap  total_revenue      volume
ticker date
A      1999-12-31         15.357   34402.898 2303600128.000 3535119.750
       2000-01-07         16.176   28925.000 2339699968.000 2940220.000
       2000-01-14         16.108   30429.100 2375800064.000 1128120.125
       2000-01-21         14.789   30593.801 2411899904.000 1547375.000
       2000-01-28         11.629   30763.100 2448000000.000  965640.000
...                          ...         ...            ...         ...
ZZ     2013-02-15          0.100     221.100          0.000  210580.000
       2013-02-22          0.084     220.100          0.000  834375.000
       2013-03-01          0.166     221.100          0.000  731779.938
       2013-03-08          0.156     222.100          0.000 1983840.000
       2013-03-15          0.104     221.100          0.000  533840.000

[6289699 rows x 10 columns]

### Short Volume

In [9]:
df_short_volume = sov.data("/short/volume", tickers=["AAPL","MSFT"],verbose=True, purge_cache=True)

/short/volume
Requesting URL: https://data.sov.ai/short/volume with params: {'tickers': 'AAPL,MSFT', 'parquet': 'True'}
Grabbing client side

In [10]:
df_short_volume

                   short_volume  total_volume  short_volume_ratio_exchange  \
ticker date
AAPL   2011-01-07   8893810.000  19134061.000                        0.461
       2011-01-14  11789186.000  22008065.000                        0.563
       2011-01-21  24197268.000  54387222.000                        0.439
       2011-01-28  13856925.000  31652930.000                        0.487
       2011-02-04   9718197.000  21816811.000                        0.498
...                         ...           ...                          ...
MSFT   2024-05-03   2811407.000   8361347.000                        0.360
       2024-05-10   1739553.000   4695623.000                        0.340
       2024-05-17   2262647.000   6495515.000                        0.359
       2024-05-24   1826571.000   5954805.000                        0.300
       2024-05-31    671821.000   2558950.000                        0.344

                   retail_short_ratio  institutional_short_ratio  \
ticker date
AAPL   2011-01-07               0.286                      0.628
       2011-01-14               0.303                      0.619
       2011-01-21               0.292                      0.586
       2011-01-28               0.316                      0.531
       2011-02-04               0.335                      0.528
...                               ...                        ...
MSFT   2024-05-03               0.031                      0.920
       2024-05-10               0.025                      0.937
       2024-05-17               0.019                      0.944
       2024-05-24               0.022                      0.911
       2024-05-31               0.036                      0.892

                   market_maker_short_ratio
ticker date
AAPL   2011-01-07                     0.086
       2011-01-14                     0.078
       2011-01-21                     0.121
       2011-01-28                     0.153
       2011-02-04                     0.137
...                                     ...
MSFT   2024-05-03                     0.049
       2024-05-10                     0.038
       2024-05-17                     0.037
       2024-05-24                     0.068
       2024-05-31                     0.072

[1400 rows x 6 columns]